### ISSUE TITLE
Disable browser cache automatically

### ISSUE THREAD

**Issue by BenEmdon** [joshua-arts/web-api-client#6]
After some investigation with @joshua-arts, we found that the browser is _by default_ caching responses to disk. The workaround to avoid this was to click the `disable cache` checkbox in chrome developer tools.

Would we be able to do this automatically? This might be possible by disabling the cache for the entire page https://www.willmaster.com/library/web-content-prep/preventing-browser-cache.php

**Comment by joshua-arts** [comment]
Gave this a shot, from what I understand this only prevent the page itself and the elements it loads from not caching, but won't affect the request the axios client send.

For now I think disabling using developer tools is still the best method, but I'll continue to look into a workaround for this.
